# Generated by Django 5.2.11 on 2026-02-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(help_text='Order of this step (0-based).')),
                ('step_name', models.CharField(blank=True, max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='steps/audio/%Y/%m/%d/')),
                ('transcript', models.TextField(blank=True, help_text='From STT or sent by client.')),
                ('result', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('UNSURE', 'UNSURE')], max_length=10)),
                ('result_reason', models.TextField(blank=True, help_text='Optional LLM explanation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='inspections.inspection')),
            ],
            options={
                'ordering': ['inspection', 'step_index'],
                'unique_together': {('inspection', 'step_index')},
            },
        ),
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='steps/images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.inspectionstep')),
            ],
        ),
    ]
